POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtsYWV2diIsImlkIjoiNWNiY2I0NWM2Y2NhNDllNDEzY2FhYTMzIiwiaWF0IjoxNTU1ODgxMjk1fQ.HmWVyKilGJ9bjMwNaGJgZkoN39hD1aSiVHnl42DvXVI

{
    "title": "Lorem ipsum",
    "author": "John Bro",
    "url": "www.asd.com",
    "likes": "9001",
    "userId": "5cbcb45c6cca49e413caaa33"
}
